import React, { useState } from 'react';
import { 
  Plus, 
  Search, 
  Filter, 
  Package, 
  Edit, 
  Trash2, 
  X
} from 'lucide-react';
import { Product, ERPSettings } from '../types';
import CustomFieldsForm from './CustomFieldsForm';
import CustomFieldsDetailView from './CustomFieldsDetailView';
import ConfirmModal from './ConfirmModal';
import { uploadFile } from '../imageUtils';

interface ProductsViewProps {
  products: Product[];
  addProduct: (product: Omit<Product, 'id' | 'stockLevel'> & { stockLevel?: number, customValues?: Record<string, any> }) => void;
  updateProduct: (product: Product) => void;
  deleteProduct: (id: string) => void;
  adjustProductStock: (id: string, amount: number) => void;
  categories: string[];
  units: string[];
  settings: ERPSettings;
}

export default function ProductsView({
  products,
  addProduct,
  updateProduct,
  deleteProduct,
  categories,
  settings
}: ProductsViewProps) {
  const [search, setSearch] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [showModal, setShowModal] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);

  // Dynamic Custom Fields State
  const [customValues, setCustomValues] = useState<Record<string, any>>({});

  // Delete confirm state
  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
  const [productToDeleteId, setProductToDeleteId] = useState<string | null>(null);
  const [productToDeleteName, setProductToDeleteName] = useState<string>('');

  // Form states (Only Category, Equipment Type, and Technical Specs are managed in UI)
  const [displayName, setDisplayName] = useState('');
  const [category, setCategory] = useState('');
  const [description, setDescription] = useState('');
  const [size, setSize] = useState('');
  const [measurementRange, setMeasurementRange] = useState('');
  const [images, setImages] = useState<string[]>([]);

  // Trigger modal for adding
  const handleOpenAdd = () => {
    setEditingProduct(null);
    setDisplayName('');
    setCategory(categories[0] || 'ابزار دقیق - فشار');
    setDescription('');
    setSize('');
    setMeasurementRange('');
    setImages([]);
    setCustomValues({});
    setShowModal(true);
  };

  // Trigger modal for editing
  const handleOpenEdit = (prod: Product) => {
    setEditingProduct(prod);
    setDisplayName(prod.displayName);
    setCategory(prod.category);
    setDescription(prod.description);
    setSize(prod.size || '');
    setMeasurementRange(prod.measurementRange || '');
    setImages(prod.images || []);
    setCustomValues(prod.customValues || {});
    setShowModal(true);
  };

  // Handle Save (Add / Edit)
  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();

    // Custom Fields Validation
    const moduleFields = (settings?.customFields || []).filter(f => f.module === 'products');
    for (const field of moduleFields) {
      if (field.required) {
        const val = customValues[field.id];
        if (val === undefined || val === null || val === '') {
          alert(`لطفاً فیلد سفارشی اجباری "${field.name}" را تکمیل کنید.`);
          return;
        }
      }
    }

    if (editingProduct) {
      updateProduct({
        ...editingProduct,
        displayName,
        name: displayName, // Synchronize name with displayName
        category,
        description,
        size,
        measurementRange,
        images,
        customValues
      });
    } else {
      addProduct({
        displayName,
        name: displayName,
        category,
        description,
        size,
        measurementRange,
        images,
        code: "EQ-" + Math.floor(10000 + Math.random() * 90000), // safe autogenerated technical code
        brand: "",
        modelNumber: "N/A",
        unit: "عدد",
        basePriceRIYAL: 0,
        minStockLevel: 0,
        stockLevel: 0,
        customValues
      });
    }
    setShowModal(false);
  };

  // Filters
  const filteredProducts = products.filter(p => {
    const matchesSearch = 
      p.displayName.toLowerCase().includes(search.toLowerCase()) ||
      p.category.toLowerCase().includes(search.toLowerCase()) ||
      p.description.toLowerCase().includes(search.toLowerCase());
    
    const matchesCategory = selectedCategory === 'all' || p.category === selectedCategory;

    return matchesSearch && matchesCategory;
  });

  return (
    <div className="space-y-6 animate-fade-in">
      {/* View Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">کاتالوگ تجهیزات ابزاردقیق</h1>
          <p className="text-slate-500 text-sm mt-1">تعریف مشخصات فنی، نوع تجهیزات و گروه‌بندی تخصصی کالاها</p>
        </div>
        <button 
          onClick={handleOpenAdd}
          className="px-4 py-2 bg-sky-500 hover:bg-sky-600 text-white rounded-xl text-sm font-medium transition shadow-lg shadow-sky-500/15 flex items-center gap-2"
        >
          <Plus size={16} />
          تعریف تجهیز جدید
        </button>
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col md:flex-row gap-4 bg-white p-4 rounded-xl border border-slate-100 shadow-sm">
        <div className="relative flex-1">
          <Search className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
          <input
            type="text"
            placeholder="جستجو در نوع تجهیز، دسته‌بندی یا مشخصات فنی..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pr-10 pl-4 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 transition text-right"
          />
        </div>

        <div className="relative w-full md:w-64 flex items-center gap-2">
          <Filter size={16} className="text-slate-400 flex-shrink-0" />
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="w-full border border-slate-200 rounded-lg text-sm py-2 px-3 focus:outline-none focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 transition appearance-none text-right bg-white"
          >
            <option value="all">همه دسته‌بندی‌ها</option>
            {categories.map((cat, i) => (
              <option key={i} value={cat}>{cat}</option>
            ))}
          </select>
        </div>
      </div>

      {/* Products Table Card */}
      <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-right border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-100 text-slate-500 text-xs font-bold">
                <th className="p-4 w-1/3">نوع تجهیز و نام کالا</th>
                <th className="p-4 w-1/4">دسته‌بندی</th>
                <th className="p-4 w-1/3">مشخصات فنی و توضیحات</th>
                <th className="p-4 text-center w-24">عملیات</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-slate-700 text-xs">
              {filteredProducts.map((p) => {
                return (
                  <tr key={p.id} className="hover:bg-slate-50/50 transition">
                    {/* Display Name */}
                    <td className="p-4">
                      <div className="flex items-start gap-3">
                        {p.images && p.images.length > 0 ? (
                          <img
                            src={p.images[0]}
                            alt={p.displayName}
                            className="w-12 h-12 object-cover rounded-lg border border-slate-200 bg-slate-50 flex-shrink-0"
                            referrerPolicy="no-referrer"
                          />
                        ) : (
                          <div className="w-12 h-12 rounded-lg border border-dashed border-slate-200 bg-slate-50 flex items-center justify-center text-slate-300 flex-shrink-0">
                            <Package size={18} />
                          </div>
                        )}
                        <div className="flex-1 min-w-0">
                          <div className="font-bold text-slate-800 text-sm leading-snug">{p.displayName}</div>
                          
                          <div className="flex flex-wrap gap-1.5 mt-1 text-[10px]">
                            {p.size && (
                              <span className="px-2 py-0.5 bg-slate-100 text-slate-600 rounded-md font-medium">
                                سایز: {p.size}
                              </span>
                            )}
                            {p.measurementRange && (
                              <span className="px-2 py-0.5 bg-sky-50 text-sky-700 rounded-md font-medium">
                                رنج: {p.measurementRange}
                              </span>
                            )}
                            {p.images && p.images.length > 0 && (
                              <span className="px-2 py-0.5 bg-emerald-50 text-emerald-700 rounded-md font-medium">
                                🖼️ {p.images.length} تصویر
                              </span>
                            )}
                          </div>

                          <div className="mt-1">
                            <CustomFieldsDetailView
                              module="products"
                              customFields={settings?.customFields || []}
                              customValues={p.customValues}
                            />
                          </div>
                        </div>
                      </div>
                    </td>

                    {/* Category */}
                    <td className="p-4 text-slate-600 font-medium">
                      {p.category}
                    </td>

                    {/* Technical Specifications / Description */}
                    <td className="p-4 max-w-md">
                      <p className="text-slate-500 leading-relaxed whitespace-pre-wrap line-clamp-3">
                        {p.description || 'ثبت نشده'}
                      </p>
                    </td>

                    {/* Actions */}
                    <td className="p-4">
                      <div className="flex items-center justify-center gap-2">
                        {/* Edit */}
                        <button
                          onClick={() => handleOpenEdit(p)}
                          className="p-1.5 text-slate-400 hover:text-sky-600 hover:bg-slate-50 rounded-lg transition"
                          title="ویرایش تجهیز"
                        >
                          <Edit size={14} />
                        </button>

                        {/* Delete */}
                        <button
                          onClick={() => {
                            setProductToDeleteId(p.id);
                            setProductToDeleteName(p.displayName || p.name);
                            setDeleteConfirmOpen(true);
                          }}
                          className="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition"
                          title="حذف تجهیز"
                        >
                          <Trash2 size={14} />
                        </button>
                      </div>
                    </td>
                  </tr>
                );
              })}

              {filteredProducts.length === 0 && (
                <tr>
                  <td colSpan={4} className="text-center p-12 text-slate-400 bg-white">
                    <Package className="mx-auto text-slate-300 mb-3" size={40} />
                    هیچ کالایی متناسب با فیلتر شما در سیستم ثبت نشده است.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Add / Edit Product Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-2xl shadow-xl border border-slate-100 w-full max-w-xl overflow-hidden animate-scale-in">
            <div className="px-6 py-4 border-b border-slate-100 flex justify-between items-center bg-slate-50">
              <h3 className="font-bold text-slate-800">
                {editingProduct ? `ویرایش اطلاعات فنی: ${editingProduct.displayName}` : 'تعریف تجهیز ابزاردقیق جدید'}
              </h3>
              <button 
                onClick={() => setShowModal(false)}
                className="p-1 hover:bg-slate-200 text-slate-500 rounded-lg transition"
              >
                <X size={18} />
              </button>
            </div>

            <form onSubmit={handleSave} className="p-6 space-y-4 max-h-[75vh] overflow-y-auto">
              <div className="space-y-4">
                
                {/* Category */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-500">دسته‌بندی تخصصی ابزاردقیق *</label>
                  <select
                    value={category}
                    onChange={(e) => setCategory(e.target.value)}
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 outline-none text-right bg-white"
                  >
                    {categories.map((cat, i) => (
                      <option key={i} value={cat}>{cat}</option>
                    ))}
                  </select>
                </div>

                {/* Equipment Type / Display Name */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-500">نوع تجهیز و نام کالا *</label>
                  <input
                    type="text"
                    required
                    value={displayName}
                    onChange={(e) => setDisplayName(e.target.value)}
                    placeholder="مثال: ترانسمیتر اختلاف فشار (DP Transmitter)"
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 outline-none text-right font-medium"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  {/* Size */}
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-slate-500">سایز (Size)</label>
                    <input
                      type="text"
                      value={size}
                      onChange={(e) => setSize(e.target.value)}
                      placeholder="مثال: '2 یا DN50"
                      className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 outline-none text-right font-medium"
                    />
                  </div>

                  {/* Measurement Range */}
                  <div className="space-y-1.5">
                    <label className="text-xs font-semibold text-slate-500">رنج اندازه‌گیری (Range)</label>
                    <input
                      type="text"
                      value={measurementRange}
                      onChange={(e) => setMeasurementRange(e.target.value)}
                      placeholder="مثال: 0 to 10 bar"
                      className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 outline-none text-right font-medium"
                    />
                  </div>
                </div>

                {/* Product Images */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-500">تصاویر محصول</label>
                  
                  {/* Drag and Drop Zone */}
                  <div className="border-2 border-dashed border-slate-250 hover:border-sky-500 rounded-xl p-4 transition text-center cursor-pointer bg-slate-50/50 hover:bg-slate-50 relative">
                    <input
                      type="file"
                      accept="image/*"
                      multiple
                      onChange={async (e) => {
                        const files = e.target.files;
                        if (files) {
                          for (const file of Array.from(files) as File[]) {
                            try {
                              const url = await uploadFile(file);
                              setImages(prev => [...prev, url]);
                            } catch (err: any) {
                              alert(err.message || 'خطا در بارگذاری تصویر محصول');
                            }
                          }
                        }
                      }}
                      className="absolute inset-0 opacity-0 cursor-pointer w-full h-full z-10"
                    />
                    <div className="text-slate-500 space-y-1">
                      <div className="text-xs font-bold text-slate-700">انتخاب یا رها کردن تصاویر کالا</div>
                      <div className="text-[10px] text-slate-400">فرمت‌های تصویری (JPG, PNG) - ذخیره‌سازی محلی</div>
                    </div>
                  </div>

                  {/* Thumbnail Previews */}
                  {images.length > 0 && (
                    <div className="grid grid-cols-4 gap-3 pt-2">
                      {images.map((img, idx) => (
                        <div key={idx} className="relative group aspect-square rounded-lg border border-slate-200 overflow-hidden bg-slate-50">
                          <img
                            src={img}
                            alt={`Product image ${idx + 1}`}
                            className="w-full h-full object-cover"
                            referrerPolicy="no-referrer"
                          />
                          <button
                            type="button"
                            onClick={() => setImages(prev => prev.filter((_, i) => i !== idx))}
                            className="absolute top-1 right-1 p-1 bg-red-600 text-white rounded-full opacity-0 group-hover:opacity-100 transition shadow-sm hover:bg-red-700 z-20"
                            title="حذف تصویر"
                          >
                            <X size={10} />
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Description / Technical Specifications */}
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-slate-500">مشخصات فنی و توضیحات</label>
                  <textarea
                    rows={4}
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="جزئیات متریال بدنه، اتصالات، کلاس کاری، رنج فشار یا دما، سیگنال خروجی و گواهینامه‌ها..."
                    className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 outline-none text-right leading-relaxed"
                  />
                </div>

                {/* Dynamic Custom Fields Form Section */}
                <CustomFieldsForm
                  module="products"
                  customFields={settings?.customFields || []}
                  customValues={customValues}
                  onChange={setCustomValues}
                />

              </div>

              <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 border border-slate-200 hover:bg-slate-50 text-slate-600 rounded-xl text-sm font-medium transition"
                >
                  انصراف
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-sky-500 hover:bg-sky-600 text-white rounded-xl text-sm font-medium transition shadow-lg shadow-sky-500/15"
                >
                  {editingProduct ? 'ثبت تغییرات تجهیز' : 'ذخیره تجهیز'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Confirm Delete Modal */}
      <ConfirmModal
        isOpen={deleteConfirmOpen}
        onClose={() => {
          setDeleteConfirmOpen(false);
          setProductToDeleteId(null);
          setProductToDeleteName('');
        }}
        onConfirm={() => {
          if (productToDeleteId) {
            deleteProduct(productToDeleteId);
          }
        }}
        title="حذف کالا/تجهیز"
        message={`آیا از حذف کالا "${productToDeleteName}" اطمینان دارید؟ این عمل غیرقابل بازگشت است.`}
      />

    </div>
  );
}
